# Generated by Django 5.2.7 on 2025-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True, help_text='Disponible para préstamo')),
                ('is_deleted', models.BooleanField(default=False, help_text='Marcado como eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['isbn'], name='books_isbn_ce4a1a_idx'), models.Index(fields=['is_available', 'is_deleted'], name='books_is_avai_e4dec9_idx')],
            },
        ),
    ]
