# Generated by Django 5.2.7 on 2025-10-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID del usuario en el microservicio de usuarios')),
                ('book_id', models.IntegerField(help_text='ID del libro en el microservicio de libros')),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('returned', 'Devuelto'), ('overdue', 'Vencido')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='loans_user_id_efac20_idx'), models.Index(fields=['book_id'], name='loans_book_id_5e4ebc_idx')],
            },
        ),
    ]
