# Generated by Django 5.0.6 on 2025-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('loan_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'loans',
            },
        ),
    ]
